# Generated by Django 5.1.5 on 2025-02-28 13:28

import User.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_perfil', models.FileField(blank=True, default='User/Base/Imagem_Perfil.png', null=True, upload_to=User.models.TheUser_Directory_Path)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('type_account', models.CharField(choices=[('Normal', 'Normal'), ('Profissional', 'Profissional')], default='Normal', max_length=20)),
                ('followers', models.ManyToManyField(related_name='myfollowers', to='User.profile')),
                ('following', models.ManyToManyField(related_name='myfollowings', to='User.profile')),
                ('friends', models.ManyToManyField(to='User.profile')),
                ('recommended', models.ManyToManyField(related_name='RecommendedTags', to='Post.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='User.theuser')),
            ],
        ),
    ]
