# Generated by Django 5.1.5 on 2025-02-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_account',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Profissional', 'Profissional')], default='Normal', max_length=20),
        ),
    ]
