# Generated by Django 5.1.5 on 2025-02-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_theuser_image_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theuser',
            name='image_perfil',
            field=models.ImageField(default='media/User/Imagem_Perfil_Vazia', upload_to='media/'),
        ),
    ]
