# Generated by Django 5.1.5 on 2025-02-26 10:58

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_perfil',
            field=models.FileField(default='User/Base/Imagem_Perfil.png', upload_to=User.models.TheUser_Directory_Path),
        ),
    ]
