# Generated by Django 5.1.5 on 2025-02-07 03:08

import User.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_theuser_image_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theuser',
            name='image_perfil',
            field=models.ImageField(default='User/Base/Imagem_Perfil.png', upload_to=User.models.TheUser_Directory_Path),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.theuser')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('post', models.FileField(upload_to=User.models.TheUser_Directory_Path)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to='User.theuser')),
                ('likes', models.ManyToManyField(blank=True, related_name='Likes', through='User.Like', to='User.theuser')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.post'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
