# Generated by Django 5.1.5 on 2025-02-26 11:34

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_profile_image_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_perfil',
            field=models.FileField(blank=True, default='User/Base/Imagem_Perfil.png', null=True, upload_to=User.models.TheUser_Directory_Path),
        ),
    ]
