# Generated by Django 5.1.5 on 2025-02-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_post_description_coment_post_coments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comentofcoment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='save',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
