# Generated by Django 5.1.5 on 2025-02-28 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=600)),
                ('muscle_group', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='', verbose_name='Training/')),
                ('video', models.FileField(blank=True, upload_to='', verbose_name='Training/')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(blank=True)),
                ('repetitions', models.IntegerField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='Training.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(max_length=100)),
                ('exercise_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='Training.exercisetraining')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ABC', 'ABC'), ('ABCD', 'ABCD'), ('ABCDE', 'ABCDE')], max_length=5)),
                ('training', models.ManyToManyField(related_name='Trainings', to='Training.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrainingSheet', to='User.theuser')),
            ],
        ),
    ]
